spring:
  application:
    name: tuneheaven-ratings-service
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        generate_statistics: true

scheduled-tasks:
  import-song-ratings-cron: 0 5 23 * * *

csv:
  import:
    ratings-file-folder: ${ratingsfolder}
    ratings-file-mask: ^tuneheaven-songs-\d{4}-\d{2}-\d{2}\.csv$
  export:
    trending-songs-file-dir: ${trendingFolder}
    trending-songs-file-mask: trending100songs-%d.csv
    loosing-songs-file-dir: ${loosingFolder}
    loosing-songs-file-mask: songs-loosing-%d.csv,